'use strict';

Template.subpageView.helpers({
    asideSubpageTestData: function () {
        return 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem, incidunt cumque minima omnis distinctio, officiis. Ad nam, vel ipsa voluptatum et adipisci voluptatem similique! Eligendi quod similique eveniet voluptatum natus culpa fugit nostrum, exercitationem a vitae nesciunt odio adipisci aliquid totam. Quidem necessitatibus recusandae nemo accusamus omnis debitis, provident consequatur laboriosam, nam vero, quasi obcaecati eaque. Veniam nesciunt a odio culpa eveniet dolorum quasi, aliquam hic quia quae? Magni voluptatum aspernatur amet, temporibus sequi itaque, repellendus tenetur aliquam. Officiis in quisquam asperiores ut nulla. Harum, quis. Debitis cupiditate amet eveniet placeat, voluptatem. Commodi perferendis corporis dolor sit iusto, soluta tempora, libero? Suscipit quidem explicabo autem perferendis repellendus ea soluta, hic sit reprehenderit laudantium, amet illum aliquam! Magnam commodi sunt pariatur totam! Quam, facilis, sed. Qui velit mollitia ex id, alias voluptatibus nihil facere assumenda, magni, rerum laudantium nemo praesentium quasi aliquid deserunt. Qui illum, suscipit expedita odio a enim earum iure quos impedit. Incidunt, impedit vitae reprehenderit omnis nisi. Eligendi totam quaerat accusantium commodi cumque fuga sequi iste repellendus dolorem ab est debitis unde eaque, eveniet voluptatem fugit a illum labore vero rem aperiam. Necessitatibus fuga ipsum reiciendis obcaecati, quam adipisci modi suscipit perspiciatis in officia. Magni nobis facere, voluptatibus.';
    },
    articleSubpageTestData: function () {
        return 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae non iste assumenda architecto eum odit, mollitia eligendi incidunt quas. Eum sunt inventore, voluptatum architecto corporis cupiditate non quidem neque ex! Et pariatur, molestias cumque nihil perspiciatis officiis ducimus aliquid unde nam aspernatur, quaerat, sint totam recusandae distinctio dignissimos tempora alias! Hic doloribus, fugiat officia atque quod, doloremque vitae nemo vero tempora animi omnis temporibus beatae, corporis quisquam. Cumque pariatur laborum, at provident odio, saepe ipsa accusamus excepturi vitae in natus totam sit temporibus enim veritatis magnam facilis quisquam nihil, sunt nobis. Eaque sint nesciunt incidunt veritatis pariatur, dicta necessitatibus impedit! Adipisci est debitis repellendus dolorem non, fugiat quo. Quae atque, nulla quo voluptate earum deleniti dignissimos nostrum iste mollitia quaerat doloribus aut architecto ea itaque aliquam, fugit facere rerum nobis odit eligendi voluptates laborum distinctio in! Soluta nostrum ex ipsam nisi suscipit ea nam, similique, provident natus, ipsum atque, deleniti esse asperiores tempore minus? Tempora accusamus nesciunt voluptate odio libero, soluta et in, neque voluptates. Eum quaerat distinctio, corrupti veniam sapiente hic omnis libero, necessitatibus autem, reprehenderit, earum. Ratione vitae alias cumque dignissimos recusandae, aliquam, incidunt accusantium quo maiores deleniti eaque quae! Dolorem deserunt tempora similique molestiae pariatur odio quis optio perspiciatis animi! Aspernatur quo accusantium hic, eius reiciendis sapiente harum, recusandae sunt, amet nisi, iste possimus totam quis itaque maiores! Soluta ducimus quam tempore necessitatibus eveniet, totam pariatur quisquam accusantium alias maiores corrupti perferendis unde aspernatur asperiores eligendi hic maxime ipsam, sapiente itaque. Rem atque omnis ex perspiciatis facere, molestias beatae quod sed eos consequuntur dolorem placeat hic accusantium iure totam asperiores ad soluta excepturi. Modi earum ducimus, nihil doloribus non, consequuntur dignissimos quisquam nulla sit quaerat repellendus, quidem blanditiis. Sit vel placeat dolorum possimus quis consectetur nulla, beatae adipisci deleniti officiis quam neque omnis, nobis sapiente veritatis magni praesentium, laborum iusto cupiditate sunt. Veniam fuga aut rem tenetur ut ex, aliquam possimus, repudiandae, nulla dicta, quidem nemo repellat suscipit distinctio molestias totam. Nemo nobis ullam omnis non ea labore voluptatibus debitis fuga molestias, eaque similique numquam veritatis placeat tempora atque quos odit officiis pariatur ex. Repudiandae culpa, at.';
    },
    articleSubpageTestTitle: function () {
        return 'Subpage article title';
    },
    asideSubpageTestTitle: function () {
        return 'Subpage aside title';
    }
});
